### ISSUE TITLE
App does not work

### ISSUE THREAD

**Issue by gomgomshrimp** [faisalsayed10/carbon-slack#2]
I added the carbon for slack app and submit with message, code etc. 
But nothing happened.

**Comment by faisalsayed10** [comment]
Hi @gomgomshrimp, I just tested it and it's working fine, can you maybe try again or share a screenshot of what values you are sending
<img width="891" alt="image" src="https://user-images.githubusercontent.com/36627266/190616762-3d4fd864-3106-4861-befd-2c4770e4424e.png">

**Comment by gomgomshrimp** [comment]
Hi @faisalsayed10 , I just attach a screenshot. But no other information because nothing changes after submit.
<img width="545" alt="스크린샷 2022-09-19 14 01 42" src="https://user-images.githubusercontent.com/12162614/190952683-5a07fbab-8fba-4391-bae4-24c160953ffd.png">

**Comment by faisalsayed10** [comment]
@gomgomshrimp I was able to understand what the issue was and it is now resolved!

thanks for reporting!

**Comment by gomgomshrimp** [comment]
@faisalsayed10 The app still does not work. Should I need to uninstall the app and add it again?

**Comment by faisalsayed10** [comment]
yeah maybe you should try that, or else i have no idea what's going on, if possible can you please share a video recording (try waiting upto 30 seconds after u hit submit on the modal in slack)
